// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcieosldznfdwucbupti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjaWVvc2xkem5mZHd1Y2J1cHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjA4NzUsImV4cCI6MjA2NzQ5Njg3NX0.cWeMqmad7ia1cy-6lPhRTDxmea5jQZ6pAi3kEJiGPZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});